
package kasir_umkm;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStream;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.view.JasperViewer;

public class MENU_TRANSAKSI extends javax.swing.JFrame {
    private DefaultTableModel model = null;
    private PreparedStatement state;
    private ResultSet rs;
    KONEKSI k = new KONEKSI();
    
    public MENU_TRANSAKSI() {
        initComponents();
        k.connect();
        refreshTable();
        refreshCombo();
        
    }

  
    class transaksi extends MENU_TRANSAKSI{
        int id_transaksi, id_barang,harga,jumlah_beli,total_bayar;
        String nama_pelanggan,tanggal,nama_barang;
        
        public transaksi(){
            this.nama_pelanggan = txt_nama_pelanggan.getText();
            String combo = box_id_barang.getSelectedItem().toString();
            String[] arr = combo.split(":");
            this.id_barang = Integer.parseInt(arr[0]);
            try {
              Date date = txt_tanggal.getDate();
                DateFormat dateformat = new SimpleDateFormat("YYYY-MM-dd");
                this.tanggal = dateformat.format(date);
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(null, e.getMessage());
            }
            this.nama_barang = arr[1];
            this.harga = Integer.parseInt(arr[2]);
            this.jumlah_beli = Integer.parseInt(txt_jumlah_beli.getText());
            this.total_bayar = this.harga * this.jumlah_beli;
        }
    }
    public void refreshTable(){
        model = new DefaultTableModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama Pelaggan");
        model.addColumn("ID Barang");
        model.addColumn("Tanggal");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Jumlah Beli");
        model.addColumn("Total Bayar");
        tabel_transaksi.setModel(model);
        try {
          this.state = k.getCon().prepareStatement("select * from transaksi");
          this.rs = this.state.executeQuery();
            while (rs.next()) {
                Object [] data ={
                 rs.getString(1),
                 rs.getString(2),
                 rs.getString(3),
                 rs.getString(4),
                 rs.getString(5),
                 rs.getString(6),
                 rs.getString(7),
                 rs.getString(8)
            };
              model.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        txt_id_transaksi.setText("");
        txt_nama_pelanggan.setText("");
        txt_jumlah_beli.setText("");
        txt_total_bayar.setText("");
    }
    public void refreshCombo(){
        try {
           this.state= k.getCon().prepareStatement("select * from barang where status='Tersedia'");
           this.rs = this.state.executeQuery();
            while (rs.next()) {                
               box_id_barang.addItem(rs.getString("id_barang")+":"+
              rs.getString("nama_barang")+":"+rs.getString("harga"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        b_cetak_laporan = new javax.swing.JButton();
        b_delete = new javax.swing.JButton();
        b_update = new javax.swing.JButton();
        b_input = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_id_transaksi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama_pelanggan = new javax.swing.JTextField();
        box_id_barang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_tanggal = new com.toedter.calendar.JDateChooser();
        txt_jumlah_beli = new javax.swing.JTextField();
        txt_total_bayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_kembali = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_transaksi);

        b_cetak_laporan.setBackground(new java.awt.Color(0, 102, 102));
        b_cetak_laporan.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        b_cetak_laporan.setForeground(new java.awt.Color(255, 255, 255));
        b_cetak_laporan.setText("CETAK LAPORAN");
        b_cetak_laporan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_cetak_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cetak_laporanActionPerformed(evt);
            }
        });

        b_delete.setBackground(new java.awt.Color(0, 102, 102));
        b_delete.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        b_delete.setForeground(new java.awt.Color(255, 255, 255));
        b_delete.setText("HAPUS");
        b_delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_deleteActionPerformed(evt);
            }
        });

        b_update.setBackground(new java.awt.Color(0, 102, 102));
        b_update.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        b_update.setForeground(new java.awt.Color(255, 255, 255));
        b_update.setText("RUBAH");
        b_update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_updateActionPerformed(evt);
            }
        });

        b_input.setBackground(new java.awt.Color(0, 102, 102));
        b_input.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        b_input.setForeground(new java.awt.Color(255, 255, 255));
        b_input.setText("INPUT");
        b_input.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_inputActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_id_transaksi.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Transaksi");

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pelanggan");

        txt_nama_pelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nama_pelangganKeyPressed(evt);
            }
        });

        box_id_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_id_barangActionPerformed(evt);
            }
        });
        box_id_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                box_id_barangKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Barang");

        jLabel6.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tanggal");

        jLabel9.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jumlah Beli");

        txt_jumlah_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlah_beliActionPerformed(evt);
            }
        });
        txt_jumlah_beli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jumlah_beliKeyPressed(evt);
            }
        });

        txt_total_bayar.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Bayar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nama_pelanggan)
                    .addComponent(txt_id_transaksi)
                    .addComponent(txt_total_bayar)
                    .addComponent(box_id_barang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(txt_jumlah_beli))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box_id_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jumlah_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 24)); // NOI18N
        jLabel1.setText(" TRANSAKSI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        b_kembali.setBackground(new java.awt.Color(0, 102, 102));
        b_kembali.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 11)); // NOI18N
        b_kembali.setForeground(new java.awt.Color(255, 255, 255));
        b_kembali.setText("KEMBALI");
        b_kembali.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_kembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_input, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_cetak_laporan)
                        .addGap(18, 18, 18)
                        .addComponent(b_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE))
                .addGap(17, 17, 17))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_kembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_update, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_input, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_cetak_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void box_id_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_id_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_id_barangActionPerformed

    private void txt_jumlah_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlah_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlah_beliActionPerformed

    private void b_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_inputActionPerformed
        // TODO add your handling code here:
        try {
           transaksi tran = new transaksi();
           txt_total_bayar.setText(""+tran.total_bayar);
           this.state = k.getCon().prepareStatement("insert into transaksi values (?,?,?,?,?,?,?,?)");
           this.state.setInt(1, 0);
           this.state.setString(2, tran.nama_pelanggan);
           this.state.setInt(3, tran.id_barang);
           this.state.setString(4, tran.tanggal);
           this.state.setString(5, tran.nama_barang);
           this.state.setInt(6, tran.harga);
           this.state.setInt(7, tran.jumlah_beli);
           this.state.setInt(8, tran.total_bayar);
           state.executeUpdate();
           //txt_tanggal.setSelectableDateRange(date 1, date1 2);
           int pilihan = JOptionPane.showConfirmDialog(null,
            "tanggal         : "+tran.tanggal+
           "\nNama           : "+tran.nama_pelanggan+
           "\nPembelian      : "+tran.jumlah_beli+" "+tran.nama_barang+
           "\nTotal Bayar    : "+tran.total_bayar+"\n",
                   "Apakah Data Transaksi Benar?",
                   JOptionPane.YES_NO_OPTION);
                  if(pilihan== JOptionPane.NO_OPTION){
                      }else if(pilihan == JOptionPane.YES_OPTION){
                          refreshTable();
                   }
                          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Mohon isi data dengan benar");
        }
    }//GEN-LAST:event_b_inputActionPerformed

    private void b_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_updateActionPerformed
        // TODO add your handling code here:
        try {
            transaksi tran = new transaksi();
            tran.id_transaksi = Integer.parseInt(txt_id_transaksi.getText());
            this.state = k.getCon().prepareStatement("update transaksi set nama_pelanggan=?,"
                    + "id_barang=?,tanggal=?,nama_barang=?,harga=?,jumlah_beli=?,total_bayar=? where id_transaksi=?");
            this.state.setString(1, tran.nama_pelanggan);
            this.state.setInt(2, tran.id_barang);
            this.state.setString(3, tran.tanggal);
            this.state.setString(4, tran.nama_barang);
            this.state.setInt(5, tran.harga);
            this.state.setInt(6, tran.jumlah_beli);
            this.state.setInt(7, tran.total_bayar);
            this.state.setInt(8, tran.id_transaksi);
            this.state.executeUpdate();
            refreshTable();
        } catch (Exception e) {
            //System.err.println("Silahkan Pilih terlebih Dahulu!");
            JOptionPane.showMessageDialog(null, "Silahkan pilih terlebih dahulu data yang mau di RUBAH!");
           // JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_b_updateActionPerformed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
        // TODO add your handling code here:
        txt_id_transaksi.setText(model.getValueAt(tabel_transaksi.getSelectedRow(), 0).toString());
        txt_nama_pelanggan.setText(model.getValueAt(tabel_transaksi.getSelectedRow(), 1).toString());
        txt_jumlah_beli.setText(model.getValueAt(tabel_transaksi.getSelectedRow(), 6).toString());
        txt_total_bayar.setText(model.getValueAt(tabel_transaksi.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    private void b_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_deleteActionPerformed
        // TODO add your handling code here:
        try {
            transaksi tran = new transaksi();
            tran.id_transaksi = Integer.parseInt(txt_id_transaksi.getText());
           this.state = k.getCon().prepareStatement("delete from transaksi where id_transaksi=?");
           this.state.setInt(1, tran.id_transaksi);
           this.state.executeUpdate();
           refreshTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Silahkan pilih terlebih dahulu data yang mau di HAPUS!");
           // JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_b_deleteActionPerformed

    private void b_cetak_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cetak_laporanActionPerformed
        try {
          File namafile = new File ("src/Laporan/kasirLAPORAN.jasper");
          JasperPrint jp = JasperFillManager.fillReport(namafile.getPath(), null, k.getCon());
          JasperViewer.viewReport(jp,false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }

// try {
//    InputStream laporanStream = getClass().getResourceAsStream("Kasir_UMKM/src/LAPORAN1/kasirLAPORAN.jasper");
//    System.out.println("File ditemukan: " + laporanStream != null);
//
//    if (laporanStream == null) {
//        throw new FileNotFoundException();
//    }
//    JasperPrint jp = JasperFillManager.fillReport(laporanStream, null, k.getCon());
//    JasperViewer.viewReport(jp, true);
//} catch (Exception e) {
//    e.printStackTrace(); 
//}
    }//GEN-LAST:event_b_cetak_laporanActionPerformed

    private void txt_nama_pelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_pelangganKeyPressed
      if (evt.getKeyCode()== KeyEvent.VK_ENTER){
         if (txt_nama_pelanggan.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Jangan Di Kosongkan","PERINGATAN!",JOptionPane.WARNING_MESSAGE);
             }else{
             box_id_barang.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_nama_pelangganKeyPressed

    private void box_id_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_box_id_barangKeyPressed
//       if (evt.getKeyCode()== KeyEvent.VK_ENTER){
//         if (box_id_barang.get().isEmpty()){
//             JOptionPane.showMessageDialog(null, "Pilih Terlebih Dahulu","PERINGATAN!",JOptionPane.WARNING_MESSAGE);
//             }else{
//             txt_tanggal.requestFocus();
//            }
//        }
    }//GEN-LAST:event_box_id_barangKeyPressed

    private void txt_jumlah_beliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlah_beliKeyPressed
      if (evt.getKeyCode()== KeyEvent.VK_ENTER){
         if (txt_jumlah_beli.getText().isEmpty()){
             JOptionPane.showMessageDialog(null, "Jangan Di Kosongkan","PERINGATAN!",JOptionPane.WARNING_MESSAGE);
             }else{
             b_input.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_jumlah_beliKeyPressed

    private void b_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_kembaliActionPerformed
        MENU_UTAMA utama = new MENU_UTAMA();
        utama.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_b_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_TRANSAKSI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_TRANSAKSI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton b_cetak_laporan;
    public javax.swing.JButton b_delete;
    public javax.swing.JButton b_input;
    private javax.swing.JButton b_kembali;
    public javax.swing.JButton b_update;
    private javax.swing.JComboBox<String> box_id_barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_transaksi;
    private javax.swing.JTextField txt_id_transaksi;
    private javax.swing.JTextField txt_jumlah_beli;
    private javax.swing.JTextField txt_nama_pelanggan;
    private com.toedter.calendar.JDateChooser txt_tanggal;
    private javax.swing.JTextField txt_total_bayar;
    // End of variables declaration//GEN-END:variables
}
